# Generated by Django 5.1.7 on 2025-03-29 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstituteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('rank', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('contact', models.TextField()),
                ('status', models.CharField(choices=[('Closed', 'Closed'), ('Apply', 'Apply')], default='Closed', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='institutes/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CC.category')),
            ],
        ),
    ]
