# Generated by Django 5.1.7 on 2025-03-29 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CC', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instituteinfo',
            name='image',
        ),
        migrations.CreateModel(
            name='InstituteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='institutes/')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='CC.instituteinfo')),
            ],
        ),
    ]
